### ISSUE TITLE
Only one organisation can be created per account 

### ISSUE THREAD

**Issue by geomenke** [kartoza/projecta#768]
It seems that only one organisation can be created from a login account.  The folks at Camptocamp have two separate organisations (companies) and are unable to create the second organisation from their login.

**Comment by timlinux** [comment]
@sonlinux please check the data model and add 1-2-m support for users and organisations. Be careful to migrate all existing data cleanly.

**Comment by timlinux** [comment]
Can you follow up on this please @sonlinux  - check with different user account levels via unit tests and reference this issue in the test comment.

**Comment by sonlinux** [comment]
@geomenke I have written some tests to show that a single log in account can create multiple organisations.
The issue seems to have been fixed.

**Comment by yjacolin** [comment]
I don't know if it is in production but here my feedback:
* in QGIS project, I still can't create another organization (e.g. Camptocamp France SAS) see http://changelog.qgis.org/en/qgis/certifyingorganisation/list/ (there is only Camptocamp SA (CH))
* in root project, I can create more than one organization. I created Camptocamp France SAS in the past but can't edit it anymore (except if I didn't create it, I do not remember anymore).
